server.port=8080
spring.application.name=train-system
spring.datasource.url=jdbc:sqlite:data/trainsys.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
mybatis-plus.configuration.map-underscore-to-camel-case=true

logging.level.trainsys=INFO
logging.level.org.springframework=INFO
